In [34]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

In [51]:
df=pd.read_csv("Book 6.csv")

In [36]:
df.head()

,BENZOL WASHER,SUM1,SUM2,SUM3,SUM4,SUM5,SUM6,SUM7,SUM8,SUM9,...,year2,SUM25,SUM26,SUM27,SUM28,SUM29,SUM30,SUM31,SUM32,year3
0,BENZOL WASHER INLET GAS TEMP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00000,0.000000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000000,0.000000
1,BENZOL WASHER OUTLET GAS TEMP,832.12,865.87,1017.63,325.08,0.00,417.39,417.39,325.08,0.00,...,0.00000,0.000000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000000,0.000000
2,BENZOL WASHER INLET OIL TEMP,0.00,0.00,9.22,0.00,0.00,0.00,0.00,0.00,0.00,...,26.56000,0.000000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000000,0.000000
3,BENZOL WASHER INLET GAS PRESSURE,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,11472.68525,998.241333,955.12,955.12,988.31,1312.58,1056.159667,976.52,1094.124333,8336.175333
4,BENZOL WASHER OUTLET GAS PRESSURE,249.20,258.82,286.16,286.98,266.81,250.10,250.10,286.98,266.81,...,98.25000,0.000000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000000,0.000000

In [52]:
df1=df.T

In [38]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,10
BENZOL WASHER,BENZOL WASHER INLET GAS TEMP,BENZOL WASHER OUTLET GAS TEMP,BENZOL WASHER INLET OIL TEMP,BENZOL WASHER INLET GAS PRESSURE,BENZOL WASHER OUTLET GAS PRESSURE,BENZOL WASHER RESISTANCE,BENZOL WASHER LEVEL,RICH OIL FLOW(M3/hr),Gas Generation ( NM3 ),GAS YIELD,GAS consumption ( NM3 )
SUM1,0.0,832.12,0.0,0.0,249.2,0.0,445.66,1616.24,31183536.0,10365.86238,234912.0
SUM2,0.0,865.87,0.0,0.0,258.82,-258.82,523.83,1729.06,27874104.0,9376.399731,0.0
SUM3,0.0,1017.63,9.22,0.0,286.16,-275.17,628.99,1812.44,30765136.0,10097.74743,0.0
SUM4,0.0,325.08,0.0,0.0,286.98,-286.98,417.21,1859.93,32337346.0,10575.46462,0.0

In [53]:
df1.isnull

<bound method DataFrame.isnull of                                          0                               1   \
BENZOL WASHER  BENZOL WASHER INLET GAS TEMP  BENZOL WASHER  OUTLET GAS TEMP
SUM1                                    0.0                          832.12
SUM2                                    0.0                          865.87
SUM3                                    0.0                         1017.63
SUM4                                    0.0                          325.08
SUM5                                    0.0                             0.0
SUM6                                    0.0                          417.39
SUM7                                    0.0                          417.39
SUM8                                    0.0                          325.08
SUM9                                    0.0                             0.0
SUM10                                   0.0                          417.39
SUM11                                   0.0                          385.56
SUM12                                   0.0                          385.56
year1                                   0.0                         5389.07
SUM13                                   0.0                             0.0
SUM14                                   0.0                             0.0
SUM15                                   0.0                             0.0
SUM16                                   0.0                             0.0
SUM17                                   0.0                             0.0
SUM18                                   0.0                             0.0
SUM19                                   0.0                             0.0
SUM20                                   0.0                             0.0
SUM21                                   0.0                             0.0
SUM22                                   0.0                             0.0
SUM23                                   0.0                             0.0
SUM24                                   0.0                             0.0
year2                                   0.0                             0.0
SUM25                                   0.0                             0.0
SUM26                                   0.0                             0.0
SUM27                                   0.0                             0.0
SUM28                                   0.0                             0.0
SUM29                                   0.0                             0.0
SUM30                                   0.0                             0.0
SUM31                                   0.0                             0.0
SUM32                                   0.0                             0.0
year3                                   0.0                             0.0

                                          2   \
BENZOL WASHER  BENZOL WASHER  INLET OIL TEMP
SUM1                                     0.0
SUM2                                     0.0
SUM3                                    9.22
SUM4                                     0.0
SUM5                                     0.0
SUM6                                     0.0
SUM7                                     0.0
SUM8                                     0.0
SUM9                                     0.0
SUM10                                    0.0
SUM11                                  31.37
SUM12                                  31.37
year1                                  71.96
SUM13                                    0.0
SUM14                                    0.0
SUM15                                    0.0
SUM16                                  26.56
SUM17                                    0.0
SUM18                                    0.0
SUM19                                    0.0
SUM20                                    0.0
SUM21                                    0.0
SUM22                                    0.0
SUM23                                    0.0
SUM24                                    0.0
year2                                  26.56
SUM25                                    0.0
SUM26                                    0.0
SUM27                                    0.0
SUM28                                    0.0
SUM29                                    0.0
SUM30                                    0.0
SUM31                                    0.0
SUM32                                    0.0
year3                                    0.0

                                              3   \
BENZOL WASHER  BENZOL WASHER  INLET GAS PRESSURE
SUM1                                         0.0
SUM2                                         0.0
SUM3                                         0.0
SUM4                                         0.0
SUM5                                         0.0
SUM6                                         0.0
SUM7                                         0.0
SUM8                                         0.0
SUM9                                         0.0
SUM10                                        0.0
SUM11                                        0.0
SUM12                                        0.0
year1                                        0.0
SUM13                                     986.05
SUM14                                   894.7225
SUM15                                     968.26
SUM16                                  906.79537
SUM17                                    1015.44
SUM18                                   1035.896
SUM19                                    1015.44
SUM20                                 996.641379
SUM21                                     819.09
SUM22                                     819.09
SUM23                                    1008.28
SUM24                                    1006.98
year2                                11472.68525
SUM25                                 998.241333
SUM26                                     955.12
SUM27                                     955.12
SUM28                                     988.31
SUM29                                    1312.58
SUM30                                1056.159667
SUM31                                     976.52
SUM32                                1094.124333
year3                                8336.175333

                                              4                         5   \
BENZOL WASHER  BENZOL WASHER OUTLET GAS PRESSURE  BENZOL WASHER RESISTANCE
SUM1                                       249.2                       0.0
SUM2                                      258.82                   -258.82
SUM3                                      286.16                   -275.17
SUM4                                      286.98                   -286.98
SUM5                                      266.81                   -266.81
SUM6                                       250.1                       0.0
SUM7                                       250.1                       0.0
SUM8                                      286.98                   -286.98
SUM9                                      266.81                   -266.81
SUM10                                      250.1                       0.0
SUM11                                     285.96                   -285.96
SUM12                                     285.96                   -285.96
year1                                    3223.98                  -2213.49
SUM13                                        0.0                       0.0
SUM14                                        0.0                       0.0
SUM15                                        0.0                       0.0
SUM16                                        0.0                     11.93
SUM17                                        0.0                       0.0
SUM18                                        0.0                       0.0
SUM19                                      33.75                       0.0
SUM20                                        0.0                       0.0
SUM21                                      32.25                       0.0
SUM22                                      32.25                       0.0
SUM23                                        0.0                       0.0
SUM24                                        0.0                       0.0
year2                                      98.25                     11.93
SUM25                                        0.0                       0.0
SUM26                                        0.0                     24.16
SUM27                                        0.0                     24.16
SUM28                                        0.0                      12.4
SUM29                                        0.0                       0.0
SUM30                                        0.0                       0.0
SUM31                                        0.0                       0.0
SUM32                                        0.0                       0.0
year3                                        0.0                     60.72

                                6                     7   \
BENZOL WASHER  BENZOL WASHER LEVEL  RICH OIL FLOW(M3/hr)
SUM1                        445.66               1616.24
SUM2                        523.83               1729.06
SUM3                        628.99               1812.44
SUM4                        417.21               1859.93
SUM5                        506.79               1756.32
SUM6                        446.47               1595.38
SUM7                        446.47               1595.38
SUM8                        417.21               1859.93
SUM9                        506.79               1756.32
SUM10                       446.47               1595.38
SUM11                       729.78               1920.04
SUM12                       729.78               1920.04
year1                      6245.45              21016.46
SUM13                       284.35               -284.35
SUM14                   261.300357                   0.0
SUM15                       291.31               -242.82
SUM16                   280.806429           -189.259524
SUM17                       288.03               -164.41
SUM18                      287.773           -263.083929
SUM19                       288.49               -239.36
SUM20                   279.289333           -230.556786
SUM21                        248.5                -223.2
SUM22                        248.5                -223.2
SUM23                       283.75               -228.84
SUM24                       287.98               -237.27
year2                  3330.079119                   0.0
SUM25                   288.010667           -288.010667
SUM26                       276.41               -252.25
SUM27                       276.41               -252.25
SUM28                       286.44               -248.52
SUM29                       277.87               -214.85
SUM30                      273.079           -259.449333
SUM31                       247.05                   0.0
SUM32                   275.672667           -262.549333
year3                  2200.942333          -1777.879333

                                   8            9                         10
BENZOL WASHER  Gas Generation ( NM3 )   GAS YIELD   GAS consumption  ( NM3 )
SUM1                       31183536.0  10365.86238                  234912.0
SUM2                       27874104.0  9376.399731                       0.0
SUM3                       30765136.0  10097.74743                       0.0
SUM4                       32337346.0  10575.46462                       0.0
SUM5                      1072364.129     344.6586                       0.0
SUM6                       33243288.0  10684.41659                       0.0
SUM7                       33243288.0  10684.41659                       0.0
SUM8                       32337346.0  10575.46462                       0.0
SUM9                      1072364.129     344.6586                       0.0
SUM10                      33243288.0  10684.41659                       0.0
SUM11                      29195096.0  10129.84264                    2217.0
SUM12                      30696696.0  9973.079996                       0.0
year1                     316263852.3  103836.4284                  237129.0
SUM13                      33569760.0  10721.16239                       0.0
SUM14                      29347584.0          0.0                       0.0
SUM15                      1057114.29       338.05                       0.0
SUM16                      33166440.0          0.0                 2862536.0
SUM17                      29001624.0  9630.633026                 2688644.0
SUM18                      28633872.0  9823.977875                 2636882.0
SUM19                      30357600.0    10474.884                 2391070.0
SUM20                      28998288.0  10053.55729                 2901133.0
SUM21                      30757104.0  11349.68299                 2763701.0
SUM22                      28935336.0  9925.120236                 2483027.0
SUM23                      32776152.0  14223.63443                 3016676.0
SUM24                      29999277.0   10220.5157                 2795973.0
year2                     336600151.3  96761.21413                24539642.0
SUM25                      26335944.0  9508.823952                 2834215.0
SUM26                      29191872.0  10431.19369                 2910089.0
SUM27                      29234976.0  9580.987961                 2493462.0
SUM28                      32198736.0  10467.35102                 2875035.0
SUM29                      31310040.0  9932.962839                 2317513.0
SUM30                      31432248.0  10226.47847                 2449531.0
SUM31                      30198846.0  10039.37977                 2494947.0
SUM32                      26363376.0  2455968.988                 1587884.0
year3                     236266038.0  2526156.166                19962676.0  >

In [56]:

# Calculate mean for float columns
float_columns = df1.select_dtypes(include=['float64']).columns
float_means = df1[float_columns].mean()

# Fill null values with respective column means
df1[float_columns] = df1[float_columns].fillna(float_means)

In [57]:
df1.isnull

<bound method DataFrame.isnull of                                          0                               1   \
BENZOL WASHER  BENZOL WASHER INLET GAS TEMP  BENZOL WASHER  OUTLET GAS TEMP
SUM1                                    0.0                          832.12
SUM2                                    0.0                          865.87
SUM3                                    0.0                         1017.63
SUM4                                    0.0                          325.08
SUM5                                    0.0                             0.0
SUM6                                    0.0                          417.39
SUM7                                    0.0                          417.39
SUM8                                    0.0                          325.08
SUM9                                    0.0                             0.0
SUM10                                   0.0                          417.39
SUM11                                   0.0                          385.56
SUM12                                   0.0                          385.56
year1                                   0.0                         5389.07
SUM13                                   0.0                             0.0
SUM14                                   0.0                             0.0
SUM15                                   0.0                             0.0
SUM16                                   0.0                             0.0
SUM17                                   0.0                             0.0
SUM18                                   0.0                             0.0
SUM19                                   0.0                             0.0
SUM20                                   0.0                             0.0
SUM21                                   0.0                             0.0
SUM22                                   0.0                             0.0
SUM23                                   0.0                             0.0
SUM24                                   0.0                             0.0
year2                                   0.0                             0.0
SUM25                                   0.0                             0.0
SUM26                                   0.0                             0.0
SUM27                                   0.0                             0.0
SUM28                                   0.0                             0.0
SUM29                                   0.0                             0.0
SUM30                                   0.0                             0.0
SUM31                                   0.0                             0.0
SUM32                                   0.0                             0.0
year3                                   0.0                             0.0

                                          2   \
BENZOL WASHER  BENZOL WASHER  INLET OIL TEMP
SUM1                                     0.0
SUM2                                     0.0
SUM3                                    9.22
SUM4                                     0.0
SUM5                                     0.0
SUM6                                     0.0
SUM7                                     0.0
SUM8                                     0.0
SUM9                                     0.0
SUM10                                    0.0
SUM11                                  31.37
SUM12                                  31.37
year1                                  71.96
SUM13                                    0.0
SUM14                                    0.0
SUM15                                    0.0
SUM16                                  26.56
SUM17                                    0.0
SUM18                                    0.0
SUM19                                    0.0
SUM20                                    0.0
SUM21                                    0.0
SUM22                                    0.0
SUM23                                    0.0
SUM24                                    0.0
year2                                  26.56
SUM25                                    0.0
SUM26                                    0.0
SUM27                                    0.0
SUM28                                    0.0
SUM29                                    0.0
SUM30                                    0.0
SUM31                                    0.0
SUM32                                    0.0
year3                                    0.0

                                              3   \
BENZOL WASHER  BENZOL WASHER  INLET GAS PRESSURE
SUM1                                         0.0
SUM2                                         0.0
SUM3                                         0.0
SUM4                                         0.0
SUM5                                         0.0
SUM6                                         0.0
SUM7                                         0.0
SUM8                                         0.0
SUM9                                         0.0
SUM10                                        0.0
SUM11                                        0.0
SUM12                                        0.0
year1                                        0.0
SUM13                                     986.05
SUM14                                   894.7225
SUM15                                     968.26
SUM16                                  906.79537
SUM17                                    1015.44
SUM18                                   1035.896
SUM19                                    1015.44
SUM20                                 996.641379
SUM21                                     819.09
SUM22                                     819.09
SUM23                                    1008.28
SUM24                                    1006.98
year2                                11472.68525
SUM25                                 998.241333
SUM26                                     955.12
SUM27                                     955.12
SUM28                                     988.31
SUM29                                    1312.58
SUM30                                1056.159667
SUM31                                     976.52
SUM32                                1094.124333
year3                                8336.175333

                                              4                         5   \
BENZOL WASHER  BENZOL WASHER OUTLET GAS PRESSURE  BENZOL WASHER RESISTANCE
SUM1                                       249.2                       0.0
SUM2                                      258.82                   -258.82
SUM3                                      286.16                   -275.17
SUM4                                      286.98                   -286.98
SUM5                                      266.81                   -266.81
SUM6                                       250.1                       0.0
SUM7                                       250.1                       0.0
SUM8                                      286.98                   -286.98
SUM9                                      266.81                   -266.81
SUM10                                      250.1                       0.0
SUM11                                     285.96                   -285.96
SUM12                                     285.96                   -285.96
year1                                    3223.98                  -2213.49
SUM13                                        0.0                       0.0
SUM14                                        0.0                       0.0
SUM15                                        0.0                       0.0
SUM16                                        0.0                     11.93
SUM17                                        0.0                       0.0
SUM18                                        0.0                       0.0
SUM19                                      33.75                       0.0
SUM20                                        0.0                       0.0
SUM21                                      32.25                       0.0
SUM22                                      32.25                       0.0
SUM23                                        0.0                       0.0
SUM24                                        0.0                       0.0
year2                                      98.25                     11.93
SUM25                                        0.0                       0.0
SUM26                                        0.0                     24.16
SUM27                                        0.0                     24.16
SUM28                                        0.0                      12.4
SUM29                                        0.0                       0.0
SUM30                                        0.0                       0.0
SUM31                                        0.0                       0.0
SUM32                                        0.0                       0.0
year3                                        0.0                     60.72

                                6                     7   \
BENZOL WASHER  BENZOL WASHER LEVEL  RICH OIL FLOW(M3/hr)
SUM1                        445.66               1616.24
SUM2                        523.83               1729.06
SUM3                        628.99               1812.44
SUM4                        417.21               1859.93
SUM5                        506.79               1756.32
SUM6                        446.47               1595.38
SUM7                        446.47               1595.38
SUM8                        417.21               1859.93
SUM9                        506.79               1756.32
SUM10                       446.47               1595.38
SUM11                       729.78               1920.04
SUM12                       729.78               1920.04
year1                      6245.45              21016.46
SUM13                       284.35               -284.35
SUM14                   261.300357                   0.0
SUM15                       291.31               -242.82
SUM16                   280.806429           -189.259524
SUM17                       288.03               -164.41
SUM18                      287.773           -263.083929
SUM19                       288.49               -239.36
SUM20                   279.289333           -230.556786
SUM21                        248.5                -223.2
SUM22                        248.5                -223.2
SUM23                       283.75               -228.84
SUM24                       287.98               -237.27
year2                  3330.079119                   0.0
SUM25                   288.010667           -288.010667
SUM26                       276.41               -252.25
SUM27                       276.41               -252.25
SUM28                       286.44               -248.52
SUM29                       277.87               -214.85
SUM30                      273.079           -259.449333
SUM31                       247.05                   0.0
SUM32                   275.672667           -262.549333
year3                  2200.942333          -1777.879333

                                   8            9                         10
BENZOL WASHER  Gas Generation ( NM3 )   GAS YIELD   GAS consumption  ( NM3 )
SUM1                       31183536.0  10365.86238                  234912.0
SUM2                       27874104.0  9376.399731                       0.0
SUM3                       30765136.0  10097.74743                       0.0
SUM4                       32337346.0  10575.46462                       0.0
SUM5                      1072364.129     344.6586                       0.0
SUM6                       33243288.0  10684.41659                       0.0
SUM7                       33243288.0  10684.41659                       0.0
SUM8                       32337346.0  10575.46462                       0.0
SUM9                      1072364.129     344.6586                       0.0
SUM10                      33243288.0  10684.41659                       0.0
SUM11                      29195096.0  10129.84264                    2217.0
SUM12                      30696696.0  9973.079996                       0.0
year1                     316263852.3  103836.4284                  237129.0
SUM13                      33569760.0  10721.16239                       0.0
SUM14                      29347584.0          0.0                       0.0
SUM15                      1057114.29       338.05                       0.0
SUM16                      33166440.0          0.0                 2862536.0
SUM17                      29001624.0  9630.633026                 2688644.0
SUM18                      28633872.0  9823.977875                 2636882.0
SUM19                      30357600.0    10474.884                 2391070.0
SUM20                      28998288.0  10053.55729                 2901133.0
SUM21                      30757104.0  11349.68299                 2763701.0
SUM22                      28935336.0  9925.120236                 2483027.0
SUM23                      32776152.0  14223.63443                 3016676.0
SUM24                      29999277.0   10220.5157                 2795973.0
year2                     336600151.3  96761.21413                24539642.0
SUM25                      26335944.0  9508.823952                 2834215.0
SUM26                      29191872.0  10431.19369                 2910089.0
SUM27                      29234976.0  9580.987961                 2493462.0
SUM28                      32198736.0  10467.35102                 2875035.0
SUM29                      31310040.0  9932.962839                 2317513.0
SUM30                      31432248.0  10226.47847                 2449531.0
SUM31                      30198846.0  10039.37977                 2494947.0
SUM32                      26363376.0  2455968.988                 1587884.0
year3                     236266038.0  2526156.166                19962676.0  >